apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - image: account:latest
          name: account
          imagePullPolicy: Never
          env:
          - name: SPRING_DATA_MONGODB_HOST
            value: mongodb-service
          - name: SPRING_DATA_MONGODB_PORT
            value: "27017"
          - name: SPRING_DATA_MONGODB_DATABASE
            value: bankDB
          ports:
            - containerPort: 8080
