apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          env:
            - name: MONGO_INITDB_DATABASE
              value: bankDB
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongo-init
          hostPath:
            path: /path/to/your/docker-entrypoint-initdb.d
        - name: mongodb-data
          hostPath:
            path: /path/to/your/data/mongodb
